version: 2

updates:
  # maintain dependencies for github actions
  - directory: /
    package-ecosystem: github-actions
    schedule:
      interval: weekly
    labels:
      - '📦 flag: dependencies'
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope

  # maintain dependencies for npm packages
  - directory: /
    package-ecosystem: npm
    versioning-strategy: increase
    schedule:
      interval: weekly
    labels:
      - '📦 flag: dependencies'
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
